Cql generation drool
cqframework/cqf-tooling pull request #221
Opened 2021-04-21 21:18 UTC by jreyno77

**Description**

- Github Issue:  
- [ ] I've read the contribution guidelines 
- [ ] Code compiles without errors
- [ ] Tests are created / updated
- [ ] Documentation is created / updated

By creating this PR you acknowledge that your contribution will be licensed under Apache 2.0

2021-04-21 21:22 UTC, JPercival commented
All the code needs to be moved to the `org.opencds.cqf.tooling` package. `individual_tooling` is not a valid top-level package for this artifact.

2021-04-29 18:29 UTC, JPercival requested changes

2021-04-29 18:29 UTC, JPercival commented on pom.xml
> +            <version>3.1.1-SNAPSHOT</version>
We should only use SNAPSHOT versions when absolutely necessary. They block a release to Maven.

2021-04-29 18:29 UTC, JPercival commented on pom.xml
>                      </configuration>
This should not be disabled. The code should be updated to not have warnings, or if there are specific issues that are impossible to work around they should be suppressed individually.

As it stands the current code won't run on a Java 8 VM due to the fact some Java 9 APIS are being used. (e.g. "List.of", "Map.of")

2021-04-29 18:29 UTC, JPercival commented on pom.xml
> +                <!-- <plugin>
Lack of Javadoc is also a blocker for release to Maven.

2021-04-29 18:29 UTC, JPercival commented on src/main/java/org/opencds/cqf/tooling/Main.java
> +        System.console().readLine();
This needs to be removed.

2021-04-29 18:29 UTC, JPercival commented on src/main/java/org/opencds/cqf/tooling/cql_generation/builder/VmrToModelElmBuilder.java
> +    protected Map<String, Marker> markers = Map.of(
Several of instances things like this that won't run on Java 8.

2021-04-29 18:29 UTC, JPercival commented on src/main/java/org/opencds/cqf/tooling/cql_generation/drool/adapter/DefinitionAdapter.java
> +package org.opencds.cqf.tooling.cql_generation.drool.adapter;
Generally, an "adapter" is used to connect one interface to another. In this case a whole new object is being created, so I'd suggest using "builder" or "converter" instead. Same applies throughout.

2021-04-29 18:29 UTC, JPercival commented on src/main/java/org/opencds/cqf/tooling/utilities/ResourceUtils.java
> +          System.out.println("skip");
Should use logger.debug or logger.trace for this. It's generally considered bad practice to white debug output to stdout.

2021-04-29 18:29 UTC, JPercival commented on src/test/resources/org/opencds/cqf/individual_tooling/cql_generation/drool/visitor/Abdominal_Cramps_314c4.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file (and others) are still under the "individual_tooling" package. Needs to move to "tooling"

2021-06-16 21:22 UTC, brynrhodes requested changes
The PR shouldn't change the version to 1.3.1, should keep it at 1.3.1-SNAPSHOT. Also, this PR is changing quite a few other dependencies, can we verify those are absolutely necessary changes? It's not clear why the HAPI structure dependencies would change, for example.

2021-06-16 23:03 UTC, JPercival approved these changes

2021-06-16 23:08 UTC, brynrhodes approved these changes

2021-06-16 23:09 UTC, merged