Features cqf 984 122 test
cqframework/cqf-tooling pull request #279
Opened 2021-08-16 21:00 UTC by TychonautVII

Parameterized Mat Measures Tests

**Description**

Wanted to put in a quick PR for a slight refactor of some of the Mat Measures Tests, to see if you're alright with it. If you're cool with this general approach, it will make it faster to add in all the other measures. 

- Issues: 
- https://tracker.esacinc.com/browse/CQF-984
- https://tracker.esacinc.com/browse/CQF-1027

- [X] I've read the contribution guidelines 
- [X] Code compiles without errors
- [X] Tests are created / updated
- [N/A ] Documentation is created / updated

By creating this PR you acknowledge that your contribution will be licensed under Apache 2.0

2021-08-16 21:01 UTC, TychonautVII commented on src/test/java/org/opencds/cqf/tooling/utilities/ECQMCreatorTest.java
> +    @Test(dataProvider = "matMeasureLoader")
Using a "DataProvider" like this is the core refactor I'm thinking about for these tests

2021-08-16 21:02 UTC, TychonautVII commented on scripts/branch.sh
> +git push --set-upstream origin $branch_name
this is just a helper script meant to support the branch naming structure we seem to be using

2021-08-30 14:59 UTC, brynrhodes requested changes
Discussed on sprint 8/30, submitter suggested rejecting in favor of a refactor that preserves test method per measure.

2021-08-30 15:02 UTC, brynrhodes commented
Please preserve the method per measure

2021-09-02 17:41 UTC, merged