add measure identifier to bundle identifier
cqframework/cqf-tooling pull request #389
Opened 2022-09-01 16:00 UTC by mdnazmulkarim

**Description**

- Github Issue:  
- [ ] I've read the contribution guidelines 
- [ ] Code compiles without errors
- [ ] Tests are created / updated
- [ ] Documentation is created / updated

By creating this PR you acknowledge that your contribution will be licensed under Apache 2.0

2022-09-01 19:57 UTC, JPercival requested changes

2022-09-01 19:57 UTC, JPercival commented on src/main/java/org/opencds/cqf/tooling/measure/r4/R4MeasureProcessor.java
> +            if(refreshedMeasure.hasIdentifier()) {
We probably want to surface all identifiers

2022-09-01 19:57 UTC, JPercival commented on src/main/java/org/opencds/cqf/tooling/measure/MeasureProcessor.java
> +    protected Object getIdentifier() {
Let's make this a List of whatever dataType the Identifiers are.

2022-09-01 19:57 UTC, JPercival commented on src/main/java/org/opencds/cqf/tooling/measure/r4/R4MeasureProcessor.java
> +                this.identifier = refreshedMeasure.getIdentifier().get(0);
Also, including the identifier should be optional

2022-09-08 19:26 UTC, brynrhodes commented
Getting warnings on this trying to build locally, which fails the build at this point... please address the warnings

2022-09-08 19:58 UTC, brynrhodes commented
I also don't think it should be _just_ the measure identifier, can we append -bundle to the identifier to make it clear that it's the identifier for the bundle, not the measure?

2022-09-15 20:36 UTC, merged