Add race and ethnicity bindings to bindings collection
cqframework/cqf-tooling pull request #531
Opened 2024-06-10 17:35 UTC by bryantaustin13

Issue 443 Add race and  ethnicity bindings to spreadsheet

**Description**

visitExtensions was added to StructureDefinitionElementBindingVisitor to visit the extensions and collect the bindings especially for patient.extension:race and patient.extension:ethnicity.

- Github Issue:  
- [X ] I've read the contribution guidelines 
- [ X] Code compiles without errors
- [ ] Tests are created / updated
- [ ] Documentation is created / updated

By creating this PR you acknowledge that your contribution will be licensed under Apache 2.0

2024-07-02 17:28 UTC, c-schuler requested changes
I am not able to test anything in this PR, so I am unable to verify functionality. A few small changes requested and some comments.

Nice work!

2024-07-02 17:28 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +            else if(ed.getId().equalsIgnoreCase("patient.extension:race")
I may be missing some context, but is this really what we want here? Seems like we want to generalize this for all potential extensions with bindings, right? Something like `ed.hasExtension()` or type checking on the ElementDefinition.

2024-07-02 17:28 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +                        StringBuilder codeSystemURLs = new StringBuilder();;
Extra ";"

2024-07-02 17:28 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +                        if(null != codeSystemsMap && !codeSystemsMap.isEmpty()) {
codeSystemsMap will never be null (see line 181)

2024-07-02 17:28 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +                    } else if (valueSetVersion.length() < 1 && bindingValueSet.contains("|")) {
Is checking the valueSetVersion string length necessary here? Seems like it is set in the previous if statements. If it is necessary, use `valueSetVersion.isEmpty()`.

2024-07-02 17:28 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +        String urlValue = ed.getType().get(0).getProfile().get(0).toString();
This is set, but never used

2024-07-02 17:28 UTC, c-schuler commented on tooling/pom.xml
> +        <dependency>
I didn't notice where this dependency is being used in this PR.

2024-08-12 22:03 UTC, c-schuler commented on tooling/pom.xml
> +        <dependency>
Applied

2024-08-12 22:03 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +                        StringBuilder codeSystemURLs = new StringBuilder();;
Applied

2024-08-12 22:04 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +            else if(ed.getId().equalsIgnoreCase("patient.extension:race")
Applied

2024-08-19 21:34 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +                        if(null != codeSystemsMap && !codeSystemsMap.isEmpty()) {
Applied

2024-08-19 21:38 UTC, c-schuler commented on tooling/src/main/java/org/opencds/cqf/tooling/acceleratorkit/StructureDefinitionElementBindingVisitor.java
> +        String urlValue = ed.getType().get(0).getProfile().get(0).toString();
Applied

2024-08-19 21:40 UTC, c-schuler approved these changes
Looks good! Waiting on @brynrhodes to give the final go-ahead.

2024-08-19 21:42 UTC, brynrhodes approved these changes

2024-08-20 03:21 UTC, merged